add getAuthorizationCode
green-api/green-api-postman-collection pull request #13
Opened 2023-11-09 03:57 UTC by andreyMalyshkin

Added GetAuthorizationCode method

2023-11-14 16:15 UTC, Amele9 requested changes
Номера телефонов брать из документации или SDK (11001234567)

Зачем так много заголовков?

2023-11-14 16:15 UTC, Amele9 commented on en/collection.json
> +							"raw": "{\n    \"phoneNumber\": \"790421903509\",\n    \"name\": \"GreenApi\"\n}",
Номер телефона!

2023-11-14 16:15 UTC, Amele9 commented on en/collection.json
> +									"raw": "{\n    \"phoneNumber\": \"790421903509\",\n    \"name\": \"GreenApi\"\n}",
Номер телефона!

2023-11-14 16:15 UTC, Amele9 commented on en/collection.json
> +							"body": "{\n    \"avatar\": \"https://pps.whatsapp.net/v/t61.24694-24/255450038_606301630687404_1229899540472209484_n.jpg?stp=dst-jpg_s96x96&ccb=11-4&oh=01_AdSqyPjrKEC3j3ZOXOsakV0EUV7toKOGb7-e
Номер телефона!

2023-11-20 11:43 UTC, AknurKh commented on en/collection.json
> +							"raw": "{\n    \"phoneNumber\": \"790421903509\",\n    \"name\": \"GreenApi\"\n}",
@andreyMalyshkin Не изменил номер телефона в теле запроса

2023-11-20 11:44 UTC, AknurKh commented on en/collection.json
> +									"raw": "{\n    \"phoneNumber\": \"790421903509\",\n    \"name\": \"GreenApi\"\n}",
@andreyMalyshkin и тут тоже

2023-11-20 11:45 UTC, AknurKh commented on ru/collection.json
> +									"raw": "{\n    \"phoneNumber\": \"790421903509\",\n    \"name\": \"GreenApi\"\n}",
@andreyMalyshkin тут тоже номер

2023-11-20 11:45 UTC, AknurKh commented on ru/collection.json
> +							"raw": "{\n    \"phoneNumber\": \"790421903509\",\n    \"name\": \"GreenApi\"\n}",
@andreyMalyshkin и тут тоже

2023-11-20 11:47 UTC, AknurKh commented on ru/collection.json
> +							"raw": "{\r\n    \"chatId\": \"79309995496@c.us\",\r\n    \"message\": \"Please choose the color:\",\r\n    \"options\": [\r\n        {\r\n            \"optionName\": \"green\"\r\n        },\r
@andreyMalyshkin лучше типо такой номер писать: 79001234567

2023-11-28 06:13 UTC, merged